### ISSUE TITLE
result.response.players is empty

### ISSUE THREAD

**Issue by initialize** [liamcurry/passport-steam#10]
Same issue as here: https://github.com/liamcurry/passport-steam/issues/9

```
(...)\node_modules\passport-steam\lib\passport-steam\strategy.js:58
            id: result.response.players[0].steamid,
                                          ^
TypeError: Cannot read property 'steamid' of undefined
    at steam.getPlayerSummaries.callback ( (...)\node_modules\passport-steam\lib\passport-steam\strategy.js:66:43)
    at IncomingMessage.<anonymous> ( (...)\node_modules\passport-steam\node_modules\steam-web\lib\steam.js:218:7)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)
```
Everything looks okay in response, identifier and profile - except:
 ```
result: { response: { players: [] } }
 ```

What am I missing?

**Comment by pgrodrigues** [comment]
I'm having the same problem, any help? :s

**Comment by DeGuitard** [comment]
It gave me a headache, but I finally found out what was wrong. Then I wanted to submit a patch, but… After my git clone, I found out it was already fixed. Strange, right?

The fact is, I installed passport-steam with the command 'npm install passport-steam'. And even if the version is "0.1.4" in package.json, the code is different (coincidentally or not, especially in strategy.js around line 58). So, if you get this issue in the future / still have troubles with this, just make sure you really have the latest source.

@joercasey it's compatible with sails-generate-auth, if you add the code below in services/passport.js at line 92:
`if (profile.hasOwnProperty('displayName')) { user.username = profile.displayName; }`

**Comment by joercasey** [comment]
Oh wow, that's strange. I replaced strategy.js with the version in the repo, and it works great! Thanks @DeGuitard

**Comment by pgrodrigues** [comment]
thanks for sharing @DeGuitard :).

**Comment by pockata** [comment]
@liamcurry Can you update the npm package with the latest code from the repository? This plugin is used by around a thousand people a month, it'll probably be worth your while to update it. Thanks!

**Comment by liamcurry** [comment]
Hey sorry about that. Updated the version on NPM. Thanks guys!
