### ISSUE TITLE
Passing custom variable(s) to Steam

### ISSUE THREAD

**Issue by THE-SIMPLE-MARK** [liamcurry/passport-steam#112]
There needs to be a way to pass a custom variable of the user's choice to the Steam API which it would pass back because **there is currently no way to verify if the id came from a specific user**.

**Comment by tobbbles** [comment]
Unfortunately this is not possible. Steam only gives us a legacy OpenID 2.0 API which has no functionality for this.


> there is currently no way to verify if the id came from a specific user.
You will need to solve this in your own business logic, unfortunately.
