### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by dolanmiu** [liamcurry/passport-steam#14]
It seems like sometimes when I login, it throws this:

```
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
```

It loads the OpenAuth steam login, and then it will take forever to login, then it will throw that timed out error. It does not return me back to my website!

What is going on?

It only started happening recently.

Maybe Request is throwing the error?

https://github.com/request/request/issues/636

**Comment by mnzt** [comment]
Are you still experiencing this issue?

If so, it appears to be a problem with your own network/application, rather than the package.

**Comment by Heartz66** [comment]
I am experiencing this bug the last couple of days.

`Error: connect ETIMEDOUT 23.38.3.235:443
at Object.exports._errnoException (util.js:1022:11)
at exports._exceptionWithHostPort (util.js:1045:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)`

**Comment by mnzt** [comment]
@Heartz66 a time out isn't a bug. 

This is an issue with your network/server, and not passport-steam

**Comment by dolanmiu** [comment]
@mnzt I can confirm this

**Comment by Heartz66** [comment]
The problem is that the error throws, is there a way to handle the error so the process doesn't kill?
