### ISSUE TITLE
Why am I getting Cannot set property 'user' of undefined?

### ISSUE THREAD

**Issue by Gacnt** [liamcurry/passport-steam#17]
Not sure why I am getting this error

I have my session initialized and everything, any information would be great thanks.

**Comment by Zeikko** [comment]
I have exactly the same issue.

It is thrown from here: node_modules/passport-steam/node_modules/passport-openid/node_modules/passport/lib/passport/http/request.js:45:35

**Comment by Zeikko** [comment]
I figured out that passport-steam is not compatible with passport 0.3.0 but works fine with 0.2.2
So you should explicitly state to use 0.2.2 in your package.json:
```
"dependencies": {
    "passport": "^0.2.2",
    "passport-steam": "^0.1.6"
}
```

**Comment by Zonalhaz** [comment]
Thanks, was having this problem also.

**Comment by Max0nyM** [comment]
some fix?(

**Comment by Cuel** [comment]
Module needs to be updated to have passport-strategy as a depenency

**Comment by sturadnidge** [comment]
@cuel this module doesn't have passport as a (direct) dependency.

Everyone else - this looks pretty much unmaintained... if all you want to do is authenticate users (ie you don't want their Steam profile data), you can just use the vanilla passport-openid module and follow the passport-openid signon example with the following:
```javascript
passport.use(new OpenIdStrategy({
    profile: false,
    providerURL: 'https://steamcommunity.com/openid',
    returnURL: 'http://localhost:3000/auth/steam/return',
    realm: 'http://localhost:3000/',
    stateless: true
  },
  function(identifier, profile, done)...
```

**Comment by nahtnam** [comment]
So this is unmaintained? Should I just use the code above?

**Comment by nahtnam** [comment]
@sturadnidge Am I supposed to use regex or something to strip out the uid from the response? Right now its returning a url, http://steamcommunity.com/openid/id/<steamid>.

**Comment by sturadnidge** [comment]
@nahtnam yeh that's what I am doing... so continuing from my snippet above, the first 2 lines in the function would be:

```javascript
    // id = http://steamcommunity.com/openid/id/XXXXXXXXXXXX
    var steamId = id.split('/')[5].toString();
```

**Comment by nahtnam** [comment]
@sturadnidge I ended up doing this:
```
const uid = identifier.replace('http://steamcommunity.com/openid/id/', '');
```

**Comment by mnzt** [comment]
@nahtnam @sturadnidge use `profile.id`. It's exactly the same as `http://steamcommunity.com/openid/id/xxxxxxxxxxxxxxxxxxx`

**Comment by nahtnam** [comment]
@mnzt What do you mean?

**Comment by mnzt** [comment]
@nahtnam 

`const uid = identifier.replace('http://steamcommunity.com/openid/id/', '');` is exactly the same to `profile.id`, which is passed back in the `passport.use` function.

Example:
```js
passport.use(new OpenIdStrategy({
    providerURL: 'https://steamcommunity.com/openid',
    returnURL: 'http://localhost:3000/auth/steam/return',
    realm: 'http://localhost:3000/',
    stateless: true
  },
  function(identifier, profile, done) {
    // Return id value is: http://steamcommunity.com/openid/id/XXXXXXXXXXXX
    // Return profile.id values is: XXXXXXXXXXXX
    // See for yourself!
    console.log(profile.id)
    console.log(identifier.replace('http://steamcommunity.com/openid/id/', '');
    ...
  }
});
```

**Comment by sturadnidge** [comment]
@mnzt oh yeh? nice one, will do!

**Comment by mnzt** [comment]
@sturadnidge no worries! There's some pretty useful stuff in the profile object including avatar images, profile urls, vanity names, etc.

**Comment by nahtnam** [comment]
Oh really? If only I knew that before. I've been making a separate api call
just to get the avatar... Thanks!

**Comment by sturadnidge** [comment]
@mznt does all that come back with the standard auth call though? I thought you had to use an API key to get all that, which I'm not doing.

**Comment by mnzt** [comment]
@sturadnidge you need the API key for getting the auth call. The `profile` data is just a separate api call and formatting inside the passport-steam package.

**Comment by sturadnidge** [comment]
@mnzt nah you don't - you can do auth without an API key. This package requires the API key because it does all those profile operations under the hood, which I'd rather to do differently - I'm just using raw openid-connect, not this package.

**Comment by mnzt** [comment]
@sturadnidge oops my bad! It seems so backwards in hindsight... 

I really wish this package would become active again, or atleast start accepting pull requests.

**Comment by sturadnidge** [comment]
@mznt no worries at all! agreed re: this package, they should at least just give the name up so someone more interested can take over. 

But yeh, that was the whole reason I came in here to begin with, to show ppl you could still do just the auth just by using vanilla passport-openid with no need for an API key(setting profile:false and stateless:true is important for that!), then after auth you can pull down profile data separately using the key-protected web APIs if you want :)

**Comment by nahtnam** [comment]
Why not fork?

**Comment by sturadnidge** [comment]
@nahtnam I certainly cbf :). But in any case, I'm just after the auth and don't care much for the profile stuff, so I'd rather just stick with vanilla passport-openid and pick up any patches that go into that.

**Comment by nahtnam** [comment]
Ah kk.

Any idea what happened to @liamcurry? It would be great if he at least updated the readme.

**Comment by welps** [comment]
Are you guys still having this issue? @mnzt and I got added as collaborators so we can keep this up-to-date now.

**Comment by cmccall** [comment]
@welps great to hear. I just tried the (updated) example and see the following after redirecting back from the steam login:  \node_modules\passport-steam\lib\passport-steam\strategy.js:62
            _json: result.response.players[0],
                         ^
TypeError: Cannot read property 'response' of undefined
    at steam.getPlayerSummaries.callback (D:\tradeup\node_modules\passpor
\lib\passport-steam\strategy.js:62:26)
    at IncomingMessage.<anonymous> (D:\tradeup\node_modules\passport-stea
modules\steam-web\lib\steam.js:262:11)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by welps** [comment]
@cmccall Do you change the Steam API key to the one Valve gives you? I receive the same error if the API key is set incorrectly.

**Comment by cmccall** [comment]
@welps yep that API key was it, copy/paste error. Thanks!

**Comment by nahtnam** [comment]
Maybe add that to the readme so that other ppl don't create an issue for
the same error.

Thanks.

**Comment by mnzt** [comment]
It technically is in the README.MD. Personally I don't feel that it needs to explicitly be explained, it should naturally be inferred.

**Comment by welps** [comment]
I was going to handle this error for the reasons above, but it was actually fixed in bbd16ce9aa1889efd6aa058db1354ee337f37092 . This hasn't been published to npm though which is why people are still getting an unfriendly error from the updated example. @mnzt and I don't have access to the package on npm so we'll request that.

After we update, this package should return a `JSON response invalid, your API key is most likely wrong` error if the API key is invalid, courtesy of the steam-web package. 

----

@liamcurry , can you please add us to the collaborators list for the npm package so we can update? Thanks. https://www.npmjs.com/package/passport-steam

We have the same nicks:
https://www.npmjs.com/~welps | https://www.npmjs.com/~mnzt

**Comment by nahtnam** [comment]
:+1:

**Comment by liamcurry** [comment]
@welps @mnzt I've added you both as collaborators on NPM.
