### ISSUE TITLE
Steam web API key in js file?

### ISSUE THREAD

**Issue by rlenders** [liamcurry/passport-steam#26]
Hi there. I'm new to all this, so maybe I'm interpreting it wrong, but it seems I have to pass my Steam web API key as a parameter in JavaScript to make the "Sign in through Steam" stuff work? If that's the case, isn't it harmful to just put the API key in a JavaScript file, where all users can easily access it?

**Comment by mnzt** [comment]
Passport is for Node.js, which runs on the server. It acts as a Web server, instead of a file which runs in the browser, therefore your source code is never disclosed to the user.
