### ISSUE TITLE
Q/A with the users

### ISSUE THREAD

**Issue by mnzt** [liamcurry/passport-steam#29]
To all users of passport-steam. I'd like to open this issue to take feedback and suggestions from the users. If you would like to make a suggestion please use the following template:
## Suggestion
- Name:
- Reason:
- Example use case:

All feedback is kindly accepted, and after we gather a nice amount me and @welps will work on getting a beta branch out.

Thanks, all :)

**Comment by martinclavell** [comment]
Hey, the source works like a charm! But I couldn't make it work with routers on express, do you have any recommendation? Any previous experience? Thanks
