### ISSUE TITLE
Usage with AngularJS

### ISSUE THREAD

**Issue by Lorac** [liamcurry/passport-steam#32]
I'm trying to use this for authentication, but I don't think it's usable with AngularJS or is it? I'm getting the CORS error which make sens, because my frontend isn't being redirected. It is not being redirected because it's calling my server /auth/steam

```
$http.get('/auth/steam').then(...
```

Should I copy the long url that steam provides (like csgolounge.com does in the sign in button)?

**Comment by mnzt** [comment]
Passport-steam exposes two endpoints and middleware for node.js, it should work with everything. 

You'll want to enable CORS compliance to properly deal with steam's oath referral

**Comment by Lorac** [comment]
Yes CORS is enabled, but the problem is that my browser isn't being redirected.

**Comment by mnzt** [comment]
That sounds like a problem with your web server + angular setup, rather than passport-steam. It's hard to do much without logs/code

**Comment by Lorac** [comment]
Do you have have an example with an angularjs setup?

**Comment by mnzt** [comment]
I don't know AngularJS, sorry. However there is an Express example in this repo, which should still apply to your server.

**Comment by Lorac** [comment]
I pretty much did what it's in example you provided for the server.

**Comment by mnzt** [comment]
It should work then, as previously stated it's more than likely a problem with your setup - and without logs/code it's next to impossible to help out. Can you provide any logs or code?

**Comment by Lorac** [comment]
I'll prepare something.

**Comment by Lorac** [comment]
Oh wow I was able to fix it by instead doing an AJAX call ($http.get(...)..  ) to the /auth/steam. 
I  just did this : `$window.location.href = '/auth/steam';`

And now it works!

**Comment by mnzt** [comment]
Just seen you've fixed this, good job :)
