### ISSUE TITLE
Integrating passport-steam with koajs

### ISSUE THREAD

**Issue by RafGDev** [liamcurry/passport-steam#33]
I have changed the example passport-steam from an express based app to a koa based app. In the express version everything worked very well but when I changed the framework to koa, after I returned from the openid provider back to my app, even though the returnUrl was right, my app instantly got a 404 status. Can passport-steam along with koa-passport be used with koa.js?

**Comment by mnzt** [comment]
I personally do not know.

Can you post error logs and code snippets so I can try and debug, please?

**Comment by RafGDev** [comment]
Here is my code:  My node version is6.0.0 and my npm version is 3.8.6

    const koa = require('koa')
    const route = require("koa-route")
    const passport = require('koa-passport')
    const SteamStrategy = require('passport-steam').Strategy;

    const app = koa();


    passport.serializeUser((user, done) => {
      done(null, user);
    });
 
    passport.deserializeUser((obj, done) => {
      done(null, obj);
    });

    passport.use(new SteamStrategy({
        returnURL: 'http://localhost:3000/auth/steam/return',
        realm: 'http://localhost:3000/',
        apiKey: '5D15901CE36754875AC6A173FBEE5A8F'
       },
      (identifier, profile, done) => {
        process.nextTick(function () {
    
          profile.identifier = identifier;
	    		console.log(profile);
          return done(null, profile);
        });
      }
    ));

    app.use(passport.initialize());



    app.use(route.get('/auth/steam',
      passport.authenticate('steam')));

    app.use(route.get('/auth/steam/return',passport.authenticate('steam'), function*() {
      console.log(this.req.user);
    }));

    app.listen(3000);`


The error message I am getting is: 

    /home/rafg/Programming/random/steamOpenId/node_modules/openid/openid.js:1148
    if(params.hasOwnProperty(key) && key != 'openid.mode')
              ^

    TypeError: params.hasOwnProperty is not a function
        at _checkSignatureUsingProvider       (/home/rafg/Programming/random/steamOpenId/node_modules/openid/openid.js:1148:15)
        at _checkSignature     (/home/rafg/Programming/random/steamOpenId/node_modules/openid/openid.js:1083:5)
        at _verifyAssertionAgainstProviders       (/home/rafg/Programming/random/steamOpenId/node_modules/openid/openid.js:1047:12)
        at /home/rafg/Programming/random/steamOpenId/node_modules/openid/openid.js:1012:7
        at /home/rafg/Programming/random/steamOpenId/node_modules/openid/openid.js:545:7
        at /home/rafg/Programming/random/steamOpenId/node_modules/openid/openid.js:411:16
        at Request._callback     (/home/rafg/Programming/random/steamOpenId/node_modules/openid/openid.js:174:7)
        at Request.self.callback      (/home/rafg/Programming/random/steamOpenId/node_modules/request/request.js:200:22)
        at emitTwo (events.js:106:13)
        at Request.emit (events.js:191:7)

**Comment by mnzt** [comment]
It looks like we need to update passport-steam to include the latest version of open-id (as of https://github.com/havard/node-openid/issues/148).

I'll work on this today, and try and get something released tonight. Thank you for raising the issue :)

**Comment by mnzt** [comment]
I've had to maintain my own fork of the `passport-openid` package, as the author is inactive. Using your example, I have it working.

**Comment by RafGDev** [comment]
When I implemented the changes you did in the pull request, the error that I stated above went away. Now, passport does not go back to my returnUrl but instead it just throws a 404 "Not Found". In the /auth/steam/return route could you please put a "this.body = "test"" in it to see if passport redirected back to the returnUrl?

Thanks.

**Comment by mnzt** [comment]
the `/return` route is meant to serialize the user into a session, and not act as a page per se.

I think the issue you're experiencing is from `koa-route`, I suggest using `koa-router` - which is a far more feature-rich solution, and one that I just verified works with passport-steam

**Comment by mnzt** [comment]
@RafGDev it's published! Please just update your NPM dependencies :)
