### ISSUE TITLE
[question] Help with storing

### ISSUE THREAD

**Issue by Falden21** [liamcurry/passport-steam#46]
Is there any easy way to store this in a mongo database (using mongoose)?

With passport-local-mongoose there are several easy ways of achieving this, I was wondering if there was an easy way here aswell?

**Comment by andrewda** [comment]
Correct me if I'm wrong, but `passport-local-mongoose` seems to be a way to easily store usernames and hashed passwords in your database. The purpose of using `passport-steam` is to *not* have to store passwords in your database – they login on the Steam servers instead.

It sounds like you might be looking for a session store, though that is not what `passport-local-mongoose` does. If that's the case, checkout the [Express session store documentation](https://github.com/expressjs/session#store) and [`connect-mongo`](https://github.com/jdesboeufs/connect-mongo).

Tell me if none of this is what you're asking, but hope this helps!

**Comment by Falden21** [comment]
I'm reading these, but to make it simple. I would like to store them as a user in the database once they've logged in with steam. This way other things can be associated with them like forum posts, comments, etc.

**Comment by andrewda** [comment]
Ah okay, I understand. There is no module right now AFAIK that is taking on this task, but it's not difficult to accomplish by yourself. It shouldn't take more than ~20 lines to store all of a user's data in a MongoDB/Mongoose database.

**Comment by Falden21** [comment]
Would you mind hinting me towards the right direction to accomplish this? It would be extremely helpful.

**Comment by pgrodrigues** [comment]
I guess you just need to:
1) Create a user schema using mongoose, which will hold your users data. Be sure that schema has specific fields for `username` and other steam account data that can be useful in your app (such as `profileUrl`, `profileImageUrl`, `steamId`, etc).
2) When the user logs in and given the fact the login was successful, just check if the user exists (for example, by searching for it's `steamId` like:

```
passport.use(new SteamStrategy({
    returnURL: 'http://localhost:3000/auth/steam/return',
    realm: 'http://localhost:3000/',
    apiKey: 'your steam API key'
  }, function (identifier, profile, done) {
    var steamId = identifier.match(/\d+$/)[0];
    var profileURL = 'http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=' + 'your steam API key' + '&steamids=' + steamId;

    User.findOne({ steamId: steamId }, function (err, user) {
      if (user) {  //  If the user already exists
          // Edit fields that might be outdated such as steam user image...
      }
      else { // If the user does not exist create a new one
           request(profileURL, function (error, response, body) {
                if (!error && response.statusCode === 200) {
                     var data = JSON.parse(body);
                     var profile = data.response.players[0];

                     var user = new User();
                    user.username = profile.personaname;
                    user.profileURL = profile.profileurl;
                   user.profileImageURL = profile.avatarmedium;
                   user.steamId = steamId;

                   user.save(function (err) {
                     done(err, user);
                  });
              } else {
                 done(error, null);
              }
          });
       }
    });
```

Of course this is just a starting point, you'll have to adjust this according to your needs.

**Comment by andrewda** [comment]
Easier way to do what @pgrodrigues suggested is to just use the `update()` method's `upsert` option, which will edit a document or create one if it does not exist. For example:

```js
User.update({ steamid }, {
	$set: profile
}, {
	upsert: true
}, (err) => {
	if (err) {
		console.log(err);
	}
});
```

This will update a document with the `steamid` field equal to the `steamid` variable (using some ES6 magic on that first line... makes stuff look cleaner). Then we override the existing document with our updated profile, and, if the document does not exist, it will be created thanks to our `upsert: true` option.

**Comment by pgrodrigues** [comment]
You're right @andrewda. Either `update` or `findOneAndUpdate` with `upsert: true` it the way to go.

**Comment by Falden21** [comment]
Thanks everyone, you have been a huge help!

**Comment by pgrodrigues** [comment]
No problem :) issue can be closed.
