### ISSUE TITLE
Passport does not want to authenticate

### ISSUE THREAD

**Issue by nicovank** [liamcurry/passport-steam#51]
Hello all,
I have been faced to this problem for 5 hours now, no way to make it work.

This is my first time using this library or even OpenID and Passport, so it might be a rookie mistake. I have been scouring the Internet did not find anything.

Here's my code:

	(module.exports = exports = (function (options) {

		const _ = require("underscore");

		options = _.extend({
			port: process.env.PORT || 3000,
			env: "prod",
			secret: "Craig Sager"
		}, options);

		const winston 		= require('winston');
		options.winston	= winston;
		winston.level		= options.env;
		winston.add(winston.transports.File, { filename: 'output.log' });

		const express		= require("express");
		const bodyParser 	= require("body-parser");
		const session 		= require('express-session');
		const routes		= require("./routes")(options);

		// Passport
		const passport 	  = require('passport');
		const SteamStrategy = require('passport-steam').Strategy;

		passport.serializeUser(function (user, done) {
			done(null, user);
		});

		passport.deserializeUser(function (obj, done) {
			done(null, obj);
		});

		passport.use(new SteamStrategy({
			returnURL: 'http://localhost:3000/auth/return',
			realm: 'http://localhost:3000/',
			apiKey: options.apiKey
		},
			function (identifier, profile, done) {
				process.nextTick(function () {

					profile.identifier = identifier;
					return done(null, profile);
				});
			}
		));

		const app = express();

		app.set('views', __dirname + '/views');
		app.set('view engine', 'ejs');

		winston.log("debug", "Loaded dependencies");

		app.use(session({
			secret: options.secret,
			resave: true,
			saveUninitialized: true
		}));

		app.use(bodyParser.json());
		app.use(bodyParser.urlencoded({
			extended: true
		}));

		app.use(passport.initialize());
		app.use(passport.session());

		// Static content
		app.use(express.static(__dirname + '/../public'));
		winston.log("debug", "static files served");

		// Routes
		app.use("/", routes);
		winston.log("debug", "express routes loaded");

		return {
			// Connect to the database and start the server
			start() {
				app.listen(options.port);
				winston.info("Server started on port: " + options.port);
			}
		};
	});

And the routes:

	module.exports = exports = (function (options) {

		const express 	= require("express");
		const router	= express.Router();
		const passport 	= require("passport");

		router.get('/logout', function (req, res) {
			req.logout();
			res.redirect('/');
		});

		router.get('/', passport.authenticate('steam', { failureRedirect: '/' }), (req, res) => res.redirect("/"));

		router.get('/return',
			// Issue #37 - Workaround for Express router module stripping the full url, causing assertion to fail 
			function (req, res, next) {
				req.url = req.originalUrl;
				next();
			},
			passport.authenticate('steam', { failureRedirect: '/' }),
			function (req, res) {
				res.redirect('/');
			});

		return router;
	});

Everything seems to go fine from a user perspective, but on the server, `req.user === undefined` and `req.isAuthenticated() === false` every time, even after loggin in. I tried to stay as close as possible to the example (that was perfectly working), removed all the unnecessary code, but never got it to work.

Thanks for the help!

**Comment by nicovank** [comment]
I got some precisions on my issue:
My folder structure:

	index.js
	routes
	|__ index.js
	|__ api
		|__ index.js
	|__ auth
		|__ index.js

`auth/index.js` has all my authentication routes, and `api/index.js` is only setting up one route trying to display `req.user`. Any route I add in `auth/index.js` will work: For example: 

	router.get("/test", (req.res) => res.end(req.isAutheticated().toString))

Will work in `auth/index.js` but not in `api/index.js`.

**Comment by welps** [comment]
The code in your first post has the return URL as `http://localhost:3000/auth/return`, but the actual route to handle it is just `/return`. Is this just a typo or something?

**Comment by nicovank** [comment]
Problem solved, nothing do do with Passport or the Steam Strategy or OpenID.

I am using the Fetch specification through 'aurelia-fetch-client', and forgot to set

    {
        credentials: "same-origin"
    }
