### ISSUE TITLE
How to integrate passport-steam's express-router with react-router?

### ISSUE THREAD

**Issue by ummahusla** [liamcurry/passport-steam#54]
I just found this repo and this is exactly what I was looking for, the thing is that I'm not sure what is the best way to organise `react-router` and `express-router`. I'm not that well familiar with node yet, so any suggestion will help.

At the moment I'm looking to integrate `passport-steam` with `create-react-app`.

Thanks

**Comment by mnzt** [comment]
React-router is just a frontend 'router' used for managing pages with the virtual DOM.

You'll need to run a backend server, with, for example, express, to authenticate - see http://toon.io/understanding-passportjs-authentication-flow/.

**Comment by mnzt** [comment]
Closing as not a passport-steam issue.
