### ISSUE TITLE
Returning to different URLs

### ISSUE THREAD

**Issue by feed4rz** [liamcurry/passport-steam#56]
How do i redirect user to different URLs depending on some parameter?

For example:
User is on landing page and clicks sign in and then returns to regular index page, but at the same time if he wanted to access settings page when not logged in, after he logs in he will be redirected back on settings page.

Is there any way to make it work?

P.S. I dont wanna use anything like setting up cookies on what page he was and then reading it after he signed in and redirecting him on that page.

**Comment by mnzt** [comment]
http://stackoverflow.com/a/13336055/5081979

**Comment by mnzt** [comment]
Closing as not a passport steam issue.

**Comment by feed4rz** [comment]
Thanks anyway 👍
