### ISSUE TITLE
InternalOpenIDError: Failed to verify assertion

### ISSUE THREAD

**Issue by brunneus** [liamcurry/passport-steam#57]
Morning,

I've read all issues about this topic and none of them help me to solve this problem.

Somebody can help solve this issue?

Heres my code: 

**Server.js**

```
passport.use(new SteamStrategy({
  returnURL: 'http://localhost:3000/auth/steam/response';
  realm: 'http://localhost:3000/',
  apiKey: 'XXXXXXXXXXXX'
},
  function (identifier, profile, done) {
    process.nextTick(function () {
      profile.identifier = identifier;
      return done(null, profile);
    });
  }
));

const auth = require('./server/routes/auth');
app.use('/auth', auth);
```

**Auth.js**

```
const express = require('express');
const router = express.Router();
var passport = require('passport');

router.get('/steam',
  passport.authenticate('steam', { failureRedirect: '/' }),
  function (req, res) {
    res.redirect('/');
  });

router.get('/steam/response',
  passport.authenticate('steam', { failureRedirect: '/' }),
  function (req, res) {
    res.redirect('/');
  });

module.exports = router;
```

error: 

> openidError: { message: 'Invalid assertion response from provider' } }

Any help will be appreciated, thanks in advance

**Comment by brunneus** [comment]
The root of the problem was network restrictions, with vpn works well.

**Comment by Robinlemon** [comment]
@brunneus It is likely the package is not updated.

Try `$ npm update`, if this is unsuccessful, update your npm version via `$ npm install -g npm`

**Comment by bdefore** [comment]
I've left an answer that fixed the issue for me here: https://github.com/liamcurry/passport-steam/issues/68#issuecomment-658367752
