### ISSUE TITLE
Persistent state though sessions/cookies

### ISSUE THREAD

**Issue by Bartozzz** [liamcurry/passport-steam#66]
Passport Steam forces the strategy to be [_stateless_](https://github.com/liamcurry/passport-steam/blob/master/lib/passport-steam/strategy.js#L81). I wonder if there's a way to save persistent data (for example. though sessions/cookies/state)?

I need to save a token from the user before he requests authorization, and return it to him after the authorization has succeeded. I've already tried to save it in [sessions](https://stackoverflow.com/a/41636472), cookies, but its look like those are overwritten in the `auth/steam/callback` and I can't acces those no more.

**Comment by mnzt** [comment]
Persisting session state is outside the remit of this package. It is down to you, the developer, to manage user state.

Here's some resources to assist what you're tring to do.
https://stackoverflow.com/questions/5522020/how-do-sessions-work-in-express-js-with-node-js
https://codeforgeek.com/2015/07/using-redis-to-handle-session-in-node-js/
