### ISSUE TITLE
How to manage dynamic strategy return URL?

### ISSUE THREAD

**Issue by kamilml** [liamcurry/passport-steam#71]
How can I put multiple `returnURL` based on a cookie of my users?

**Comment by dilame** [comment]
@kamilml i just found an ideal solution
```js
const _ = require('lodash');

passport.use(new SteamStrategy({
    get returnURL() {
    return _.sample(['domain', 'another'])
  },
    get apiKey() {
      return _.sample(['key', 'another'])
    },
  },
  (identifier, profile, next) => {
    next(null, profile)
  }))
```

**Comment by mnzt** [comment]
@dilame Your solution looks good to me, will close this as resolved.

@kamilml if you're looking for something different, please contest the above solution, or open a new ticket.
