### ISSUE TITLE
OpenID returns https, "Claimed identity is invalid"

### ISSUE THREAD

**Issue by demipixel** [liamcurry/passport-steam#80]
https://github.com/liamcurry/passport-steam/blob/08c56d79a95236b08353ace632352e6d755b9387/lib/passport-steam/strategy.js#L88-L92

I don't know why (everything worked fine before, maybe steam changed something?) but I'm getting https for the identifier. Does this mean it should be `https:\/\/...` or `https?:\/\/...`?

**Comment by joshverd** [comment]
Getting this exact error right now. I have found zero documentation on what this means, but I know something did change.

**Comment by joshverd** [comment]
Ok, it looks like there is an outstanding pull request that fixes this. Valve changed something with http/https requests on the API and it's tripping up the regex. 

https://github.com/liamcurry/passport-steam/pull/74

**Comment by 54** [comment]
Yeah, I haven't dug yet to figure out what actually changed. But, FWIW, everyone's integration is currently broken. It appears to go further than just the https change as we were already prepared for that in my own implementation.

**Comment by demipixel** [comment]
Are you sure? I changed it to support https and things seem to be working on my site... odd.

**Comment by 54** [comment]
Really? Interesting.

**Comment by mnzt** [comment]
Closed by https://github.com/liamcurry/passport-steam/pull/74.
