### ISSUE TITLE
'Claimed identity is invalid'

### ISSUE THREAD

**Issue by Noobulater** [liamcurry/passport-steam#84]
My passport is giving me a failure message 'Claimed identity is invalid.' and its failing to authenticate.

This changed for my site, and I hadn't made any code changes (happened 4/7/18). This is preventing any and all logins on my site

**Comment by mnzt** [comment]
Please upgrade `passport-steam` to version '1.0.9' and this should fix your issue.

**Comment by Noobulater** [comment]
Yes this resolved my issue, thanks!
