### ISSUE TITLE
What I should do with Validate?

### ISSUE THREAD

**Issue by HulioEglesias** [liamcurry/passport-steam#90]
Why I got a error?
<img width="937" alt="2019-02-03 18 34 53" src="https://user-images.githubusercontent.com/15662060/52178712-ecc5f800-27e2-11e9-8313-603b2d262e86.png">
What I should do?

**Comment by Thomas-Smyth** [comment]
Showing your code is the only way we can help you...

**Comment by tobbbles** [comment]
@Thomas-Smyth Is right. Due to the age of this issue, I'm going to close this as becoming stale.
